### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by kierad** [gkswamy98/fast_irl#1]
Hello, thanks for sharing your code - are you able to also share a requirements.txt or a environment.yml?

**Comment by asmith26** [comment]
I would also appreciate this.

**Comment by jren03** [comment]
If you're working in a conda environment, these are the minimal packages/versions I installed to get this to work:
1. `conda create -n fast_irl python=3.9`
2. `pip install stable-baselines3==0.8.0 pybullet==3.2.1 tqdm ipykernel==6.4.1 matplotlib==3.4.3 rliable "cython<3"`

If you're working with antmaze, you'll have to install D4RL at some point as well, but there shouldn't be any conflicts. At most, you might reach a `cython` issue, which I found this [link](https://github.com/openai/mujoco-py/issues/773#issuecomment-1639684035) to be helpful for. 

Finally, in filt.py, you may want to set `outer_steps = 100` on ln82 and add in `os.makedirs(os.path.join("learners", self.env), exist_ok=True)` right before ln222.
